/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	pingcapv1alpha1 "github.com/cofyc/advanced-statefulset/pkg/apis/pingcap/v1alpha1"
	versioned "github.com/cofyc/advanced-statefulset/pkg/client/clientset/versioned"
	internalinterfaces "github.com/cofyc/advanced-statefulset/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/cofyc/advanced-statefulset/pkg/client/listers/pingcap/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AdvancedStatefulSetInformer provides access to a shared informer and lister for
// AdvancedStatefulSets.
type AdvancedStatefulSetInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.AdvancedStatefulSetLister
}

type advancedStatefulSetInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAdvancedStatefulSetInformer constructs a new informer for AdvancedStatefulSet type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAdvancedStatefulSetInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAdvancedStatefulSetInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAdvancedStatefulSetInformer constructs a new informer for AdvancedStatefulSet type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAdvancedStatefulSetInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PingcapV1alpha1().AdvancedStatefulSets(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PingcapV1alpha1().AdvancedStatefulSets(namespace).Watch(options)
			},
		},
		&pingcapv1alpha1.AdvancedStatefulSet{},
		resyncPeriod,
		indexers,
	)
}

func (f *advancedStatefulSetInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAdvancedStatefulSetInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *advancedStatefulSetInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&pingcapv1alpha1.AdvancedStatefulSet{}, f.defaultInformer)
}

func (f *advancedStatefulSetInformer) Lister() v1alpha1.AdvancedStatefulSetLister {
	return v1alpha1.NewAdvancedStatefulSetLister(f.Informer().GetIndexer())
}
