/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1 "github.com/pingcap/advanced-statefulset/client/apis/apps/v1"
	appsv1 "github.com/pingcap/advanced-statefulset/client/client/applyconfiguration/apps/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=apps.pingcap.com, Version=v1
	case v1.SchemeGroupVersion.WithKind("RollingUpdateStatefulSetStrategy"):
		return &appsv1.RollingUpdateStatefulSetStrategyApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("StatefulSet"):
		return &appsv1.StatefulSetApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("StatefulSetCondition"):
		return &appsv1.StatefulSetConditionApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("StatefulSetSpec"):
		return &appsv1.StatefulSetSpecApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("StatefulSetStatus"):
		return &appsv1.StatefulSetStatusApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("StatefulSetUpdateStrategy"):
		return &appsv1.StatefulSetUpdateStrategyApplyConfiguration{}

	}
	return nil
}
