apiVersion: v1
kind: ServiceAccount
metadata:
  name: advanced-statefulset-controller
  namespace: advanced-statefulset
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: advanced-statefulset-controller
rules:
- apiGroups:
  - apps.pingcap.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - 'apps'
  resources:
  - 'controllerrevisions'
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - 'events'
  - 'pods'
  - 'persistentvolumeclaims'
  - 'persistentvolumes'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: advanced-statefulset-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: advanced-statefulset-controller
subjects:
- kind: ServiceAccount
  name: advanced-statefulset-controller
  namespace: advanced-statefulset
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: advanced-statefulset-controller
  namespace: advanced-statefulset
rules:
- apiGroups:
  - ''
  resources:
  - 'endpoints'
  verbs:
  - '*'
- apiGroups:
  - 'coordination.k8s.io'
  resources:
  - 'leases'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: advanced-statefulset-controller
  namespace: advanced-statefulset
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: advanced-statefulset-controller
subjects:
- kind: ServiceAccount
  name: advanced-statefulset-controller
  namespace: advanced-statefulset
