/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/cofyc/advanced-statefulset/pkg/apis/pingcap/v1alpha1"
	scheme "github.com/cofyc/advanced-statefulset/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AdvancedStatefulSetsGetter has a method to return a AdvancedStatefulSetInterface.
// A group's client should implement this interface.
type AdvancedStatefulSetsGetter interface {
	AdvancedStatefulSets(namespace string) AdvancedStatefulSetInterface
}

// AdvancedStatefulSetInterface has methods to work with AdvancedStatefulSet resources.
type AdvancedStatefulSetInterface interface {
	Create(*v1alpha1.AdvancedStatefulSet) (*v1alpha1.AdvancedStatefulSet, error)
	Update(*v1alpha1.AdvancedStatefulSet) (*v1alpha1.AdvancedStatefulSet, error)
	UpdateStatus(*v1alpha1.AdvancedStatefulSet) (*v1alpha1.AdvancedStatefulSet, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.AdvancedStatefulSet, error)
	List(opts v1.ListOptions) (*v1alpha1.AdvancedStatefulSetList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AdvancedStatefulSet, err error)
	AdvancedStatefulSetExpansion
}

// advancedStatefulSets implements AdvancedStatefulSetInterface
type advancedStatefulSets struct {
	client rest.Interface
	ns     string
}

// newAdvancedStatefulSets returns a AdvancedStatefulSets
func newAdvancedStatefulSets(c *PingcapV1alpha1Client, namespace string) *advancedStatefulSets {
	return &advancedStatefulSets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the advancedStatefulSet, and returns the corresponding advancedStatefulSet object, and an error if there is any.
func (c *advancedStatefulSets) Get(name string, options v1.GetOptions) (result *v1alpha1.AdvancedStatefulSet, err error) {
	result = &v1alpha1.AdvancedStatefulSet{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("advancedstatefulsets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AdvancedStatefulSets that match those selectors.
func (c *advancedStatefulSets) List(opts v1.ListOptions) (result *v1alpha1.AdvancedStatefulSetList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.AdvancedStatefulSetList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("advancedstatefulsets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested advancedStatefulSets.
func (c *advancedStatefulSets) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("advancedstatefulsets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a advancedStatefulSet and creates it.  Returns the server's representation of the advancedStatefulSet, and an error, if there is any.
func (c *advancedStatefulSets) Create(advancedStatefulSet *v1alpha1.AdvancedStatefulSet) (result *v1alpha1.AdvancedStatefulSet, err error) {
	result = &v1alpha1.AdvancedStatefulSet{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("advancedstatefulsets").
		Body(advancedStatefulSet).
		Do().
		Into(result)
	return
}

// Update takes the representation of a advancedStatefulSet and updates it. Returns the server's representation of the advancedStatefulSet, and an error, if there is any.
func (c *advancedStatefulSets) Update(advancedStatefulSet *v1alpha1.AdvancedStatefulSet) (result *v1alpha1.AdvancedStatefulSet, err error) {
	result = &v1alpha1.AdvancedStatefulSet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("advancedstatefulsets").
		Name(advancedStatefulSet.Name).
		Body(advancedStatefulSet).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *advancedStatefulSets) UpdateStatus(advancedStatefulSet *v1alpha1.AdvancedStatefulSet) (result *v1alpha1.AdvancedStatefulSet, err error) {
	result = &v1alpha1.AdvancedStatefulSet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("advancedstatefulsets").
		Name(advancedStatefulSet.Name).
		SubResource("status").
		Body(advancedStatefulSet).
		Do().
		Into(result)
	return
}

// Delete takes name of the advancedStatefulSet and deletes it. Returns an error if one occurs.
func (c *advancedStatefulSets) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("advancedstatefulsets").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *advancedStatefulSets) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("advancedstatefulsets").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched advancedStatefulSet.
func (c *advancedStatefulSets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AdvancedStatefulSet, err error) {
	result = &v1alpha1.AdvancedStatefulSet{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("advancedstatefulsets").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
